const {PERMISSIONS} = require("./permissions");
const ROLE_PERMISSIONS = {
    student:[
        PERMISSIONS.READ_MEMBER,
        PERMISSIONS.PUT_MEMBER,
        PERMISSIONS.PATCH_MEMBER,
        PERMISSIONS.READ_BOOK,
        PERMISSIONS.CREATE_REVIEW,
        PERMISSIONS.READ_REVIEW,
        PERMISSIONS.PUT_REVIEW,
        PERMISSIONS.PATCH_REVIEW,
        PERMISSIONS.DELETE_REVIEW,
        PERMISSIONS.CREATE_LOANS
    ],
    librarian:[
        PERMISSIONS.READ_BOOK,
        PERMISSIONS.PUT_BOOK,
        PERMISSIONS.PATCH_BOOK,
        PERMISSIONS.READ_AUTHOR,
        PERMISSIONS.PUT_AUTHOR,
        PERMISSIONS.PATCH_AUTHOR,
        PERMISSIONS.READ_CATEGORIES,
        PERMISSIONS.PUT_CATEGORIES,
        PERMISSIONS.PATCH_CATEGORIES,
        PERMISSIONS.READ_PUBLISHERS,
        PERMISSIONS.PUT_PUBLISHERS,
        PERMISSIONS.PATCH_PUBLISHERS,
    ]

}
module.exports={ROLE_PERMISSIONS};
